#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for ClamAV Desktop GUI Application

set -e

echo "========================================"
echo "ClamUI Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PROJECT_DIR="/home/rooki/autoclaudeprojects/clamui"

# ============================================
# CHECK SYSTEM DEPENDENCIES
# ============================================

echo ""
echo -e "${BLUE}Checking system dependencies...${NC}"

# Check Python
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version 2>&1)
    echo -e "${GREEN}✓ Python found: $PYTHON_VERSION${NC}"
else
    echo -e "${RED}✗ Python3 not found. Please install Python 3.10+${NC}"
    exit 1
fi

# Check PyGObject
if python3 -c "import gi" &> /dev/null; then
    echo -e "${GREEN}✓ PyGObject found${NC}"
else
    echo -e "${RED}✗ PyGObject not found. Install with: pip install PyGObject${NC}"
    echo -e "${YELLOW}  Also ensure system packages: python3-gi gir1.2-gtk-4.0 gir1.2-adw-1${NC}"
fi

# Check GTK4
if python3 -c "import gi; gi.require_version('Gtk', '4.0'); from gi.repository import Gtk" &> /dev/null; then
    echo -e "${GREEN}✓ GTK4 bindings available${NC}"
else
    echo -e "${YELLOW}! GTK4 bindings may not be available${NC}"
    echo -e "${YELLOW}  Install: sudo apt install gir1.2-gtk-4.0${NC}"
fi

# Check Adwaita
if python3 -c "import gi; gi.require_version('Adw', '1'); from gi.repository import Adw" &> /dev/null; then
    echo -e "${GREEN}✓ Adwaita bindings available${NC}"
else
    echo -e "${YELLOW}! Adwaita bindings may not be available${NC}"
    echo -e "${YELLOW}  Install: sudo apt install gir1.2-adw-1${NC}"
fi

# Check ClamAV
if command -v clamscan &> /dev/null; then
    CLAM_VERSION=$(clamscan --version 2>&1 | head -1)
    echo -e "${GREEN}✓ ClamAV found: $CLAM_VERSION${NC}"
else
    echo -e "${YELLOW}! ClamAV not found (optional for development)${NC}"
    echo -e "${YELLOW}  Install: sudo apt install clamav${NC}"
fi

# ============================================
# VERIFY PROJECT STRUCTURE
# ============================================

echo ""
echo -e "${BLUE}Verifying project structure...${NC}"

cd "$PROJECT_DIR"

# Check if source directory exists
if [ -d "src" ]; then
    echo -e "${GREEN}✓ src/ directory exists${NC}"
else
    echo -e "${YELLOW}! src/ directory not found - will be created during implementation${NC}"
fi

# Check requirements.txt
if [ -f "requirements.txt" ]; then
    echo -e "${GREEN}✓ requirements.txt exists${NC}"
else
    echo -e "${YELLOW}! requirements.txt not found - will be created during implementation${NC}"
fi

# ============================================
# LAUNCH APPLICATION (if available)
# ============================================

echo ""
echo -e "${BLUE}Attempting to launch application...${NC}"

if [ -f "src/main.py" ]; then
    echo -e "${GREEN}Launching ClamUI...${NC}"
    echo "Command: python3 src/main.py"
    echo ""
    python3 src/main.py &
    APP_PID=$!
    echo -e "${GREEN}Application started with PID: $APP_PID${NC}"
else
    echo -e "${YELLOW}src/main.py not found - application not yet implemented${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: ClamUI"
echo "Directory: $PROJECT_DIR"
echo ""
echo "To run the application:"
echo "  cd $PROJECT_DIR"
echo "  python3 src/main.py"
echo ""
echo "To install dependencies:"
echo "  pip install -r requirements.txt"
echo ""
echo "System packages (if needed):"
echo "  sudo apt install python3-gi gir1.2-gtk-4.0 gir1.2-adw-1 clamav"
echo ""
